[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://afro-asia-connect.onrender.com"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_Zj2HL23sL0VeOEhcUOxth5ns"
  NEXTAUTH_URL = "https://afroasia-connect.netlify.app"
  NEXTAUTH_SECRET = "3a6c82362091d5424bbcfb25ce57ec8d6195a3c6d650f6b05f725efcfb8c7daa425616f553f4798443eff295e7efcc1d6a9b6c6ddb153297b43c62a1a6b00629"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_API_URL = "https://afroasiaconnect-api-preview.netlify.app"

[plugins]
  package = "@netlify/next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"
