[build]
  # Use standard Next.js build output directory
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  SECRETS_SCAN_ENABLED = "false"

[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_Zj2HL23sL0VeOEhcUOxth5ns"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"
